import { GeoPoint, Timestamp } from 'firebase/firestore'

import type { UserProfile } from '@/types/user'

// Location shape used inside FitlinkEvent.
// placeId is the Google Places ID - required for check-in and share deep-link.
export interface EventLocation {
  name: string
  address: string
  coordinates: GeoPoint
  placeId: string
}

// Mirrors the /events/{eventId} Firestore document schema exactly.
// matchId convention: auto-generated by Firestore (addDoc).
export interface FitlinkEvent {
  id: string
  creatorId: string
  title: string
  description: string
  activityType: string
  location: EventLocation
  startAt: Timestamp
  endAt: Timestamp
  maxAttendees: number | null
  attendees: string[]
  city: string
  country: string
  createdAt: Timestamp
  cancelled: boolean
}

// RSVP state for the current user relative to a specific event.
export type EventRSVPStatus = 'attending' | 'notAttending' | 'none'

// Enriched version with resolved attendee profiles for EventDetailScreen.
// attendeeProfiles contains only the first 5 profiles (display cap).
export interface EventWithAttendeeProfiles extends FitlinkEvent {
  attendeeProfiles: UserProfile[]
}
