export interface SeedProfileDefinition {
  avatarFile: string
  firstName: string
  dateOfBirth: string
  gender: 'male' | 'female' | 'non-binary'
  bio: string
  height: number
  activities: string[]
  fitnessLevel: 'beginner' | 'intermediate' | 'advanced' | 'athlete'
  workoutFrequency: string
  dietaryPreference: string
  fitnessGoals: string[]
  smoking: 'yes' | 'no' | 'occasionally'
  drinking: 'yes' | 'no' | 'socially'
  lookingFor: Array<'friends' | 'workout_partners' | 'dating'>
  city: string
}

export const SEED_PROFILES: SeedProfileDefinition[] = [
  {
    avatarFile: 'seed-avatar-01.svg',
    firstName: 'Aiman',
    dateOfBirth: '1997-05-12',
    gender: 'male',
    bio: 'Morning runs and iced kopi. Looking for someone to keep pace with.',
    height: 175,
    activities: ['Running', 'Cycling'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '4-5 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['Endurance', 'General fitness'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['dating', 'workout_partners'],
    city: 'Kuala Lumpur',
  },
  {
    avatarFile: 'seed-avatar-02.svg',
    firstName: 'Farid',
    dateOfBirth: '1994-11-03',
    gender: 'male',
    bio: 'Gym before work, always. Open to new lifting partners.',
    height: 180,
    activities: ['Weightlifting', 'CrossFit'],
    fitnessLevel: 'advanced',
    workoutFrequency: '6+ times a week',
    dietaryPreference: 'High protein',
    fitnessGoals: ['Strength', 'Muscle gain'],
    smoking: 'no',
    drinking: 'no',
    lookingFor: ['workout_partners', 'friends'],
    city: 'Selangor',
  },
  {
    avatarFile: 'seed-avatar-03.svg',
    firstName: 'Mei Ling',
    dateOfBirth: '1998-02-20',
    gender: 'female',
    bio: 'Yoga instructor on weekends. Balance in everything.',
    height: 162,
    activities: ['Yoga', 'Pilates'],
    fitnessLevel: 'advanced',
    workoutFrequency: '4-5 times a week',
    dietaryPreference: 'Vegetarian',
    fitnessGoals: ['Flexibility', 'Mindfulness'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['dating'],
    city: 'Kuala Lumpur',
  },
  {
    avatarFile: 'seed-avatar-04.svg',
    firstName: 'Ravi',
    dateOfBirth: '1995-08-17',
    gender: 'male',
    bio: 'Weekend cyclist, weekday desk job. Trying to even that out.',
    height: 172,
    activities: ['Cycling', 'Swimming'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '2-3 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['General fitness', 'Weight loss'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['friends', 'workout_partners'],
    city: 'Selangor',
  },
  {
    avatarFile: 'seed-avatar-05.svg',
    firstName: 'Danish',
    dateOfBirth: '1993-01-29',
    gender: 'male',
    bio: 'Boxing three times a week keeps me sane.',
    height: 178,
    activities: ['Boxing', 'HIIT'],
    fitnessLevel: 'advanced',
    workoutFrequency: '4-5 times a week',
    dietaryPreference: 'High protein',
    fitnessGoals: ['Strength', 'Endurance'],
    smoking: 'no',
    drinking: 'no',
    lookingFor: ['dating', 'workout_partners'],
    city: 'Kuala Lumpur',
  },
  {
    avatarFile: 'seed-avatar-06.svg',
    firstName: 'Siti',
    dateOfBirth: '1999-06-08',
    gender: 'female',
    bio: 'Pool laps before the sun gets too much.',
    height: 165,
    activities: ['Swimming', 'Running'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '2-3 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['Endurance', 'General fitness'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['dating', 'friends'],
    city: 'Selangor',
  },
  {
    avatarFile: 'seed-avatar-07.svg',
    firstName: 'Hafiz',
    dateOfBirth: '1996-09-22',
    gender: 'male',
    bio: 'Best conversations happen on a trail, not a couch.',
    height: 176,
    activities: ['Hiking', 'Running'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '2-3 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['General fitness', 'Endurance'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['dating', 'friends'],
    city: 'Kuala Lumpur',
  },
  {
    avatarFile: 'seed-avatar-08.svg',
    firstName: 'Nadia',
    dateOfBirth: '1997-12-05',
    gender: 'female',
    bio: 'Dance cardio over the treadmill, every time.',
    height: 160,
    activities: ['Dance', 'Pilates'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '2-3 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['General fitness', 'Flexibility'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['dating'],
    city: 'Selangor',
  },
  {
    avatarFile: 'seed-avatar-09.svg',
    firstName: 'Kevin',
    dateOfBirth: '1992-04-14',
    gender: 'male',
    bio: 'Weekends mean climbing gyms, not malls.',
    height: 174,
    activities: ['Rock climbing', 'Weightlifting'],
    fitnessLevel: 'advanced',
    workoutFrequency: '4-5 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['Strength', 'General fitness'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['workout_partners', 'friends'],
    city: 'Kuala Lumpur',
  },
  {
    avatarFile: 'seed-avatar-10.svg',
    firstName: 'Aisyah',
    dateOfBirth: '2000-07-19',
    gender: 'female',
    bio: 'Pilates reformer classes, three times a week, non-negotiable.',
    height: 158,
    activities: ['Pilates', 'Yoga'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '2-3 times a week',
    dietaryPreference: 'Vegetarian',
    fitnessGoals: ['Flexibility', 'General fitness'],
    smoking: 'no',
    drinking: 'no',
    lookingFor: ['dating', 'friends'],
    city: 'Selangor',
  },
  {
    avatarFile: 'seed-avatar-11.svg',
    firstName: 'Zack',
    dateOfBirth: '1995-03-27',
    gender: 'male',
    bio: 'Pickup basketball on Sundays. Come find me at the court.',
    height: 182,
    activities: ['Basketball', 'Running'],
    fitnessLevel: 'intermediate',
    workoutFrequency: '2-3 times a week',
    dietaryPreference: 'No restrictions',
    fitnessGoals: ['General fitness', 'Endurance'],
    smoking: 'no',
    drinking: 'socially',
    lookingFor: ['friends', 'workout_partners'],
    city: 'Kuala Lumpur',
  },
  {
    avatarFile: 'seed-avatar-12.svg',
    firstName: 'Iman',
    dateOfBirth: '1994-10-11',
    gender: 'female',
    bio: 'Muay Thai twice a week. Not here to talk about the weather.',
    height: 163,
    activities: ['Martial arts', 'HIIT'],
    fitnessLevel: 'advanced',
    workoutFrequency: '4-5 times a week',
    dietaryPreference: 'High protein',
    fitnessGoals: ['Strength', 'Endurance'],
    smoking: 'no',
    drinking: 'no',
    lookingFor: ['dating', 'workout_partners'],
    city: 'Selangor',
  },
]
